### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by RedInquisitive** [AnActualBear/SteamVRImporter#1]
```
SteamVRImporter> py .\main.py
Found Installed VR Game: Subnautica
Found Installed VR Game: NoLimits 2 Roller Coaster Simulation
Found Installed VR Game: VRChat
Found Installed VR Game: The Lab
Found Installed VR Game: cyubeVR
Found Installed VR Game: VTOL VR
Found Installed VR Game: OrbusVR
Traceback (most recent call last):
  File ".\main.py", line 135, in <module>
    vrmanifest = importVRManifest()
  File ".\main.py", line 17, in importVRManifest
    addGameFolder(app)
  File ".\main.py", line 58, in addGameFolder
    completePath = appidFolder[appid[0]] + completePath
KeyError: '264710'
```
Tried to get it working, but something caused a key error during run time. Thought I would report it!
```
"LibraryFolders"
{
	"TimeNextStatsReport"		"0000000000"
	"ContentStatsID"		"0000000000000000000"
	"1"		"E:\\Steam"
	"2"		"G:\\Steam"
}
```
This might help

**Comment by AnActualBear** [comment]
Do you have your games in more than one directory? I made some changes to the script. If it still doesn't work can you send me your steamapps.vrmanifest (Located: C:\Program Files (x86)\Steam\config)

**Comment by RedInquisitive** [comment]
I'll go ahead and pull your changes. I actually got it working within the 40 minutes since I opened this issue (I had to modify the regex for finding steam dirs). 

Let me test what you got.

**Comment by RedInquisitive** [comment]
Sorry to keep you on your toes!

Worked first try with your patch.
